if(EXISTS "/home/runner/work/omscript/omscript/build-tests3/omsc_tests[1]_tests.cmake")
  include("/home/runner/work/omscript/omscript/build-tests3/omsc_tests[1]_tests.cmake")
else()
  add_test(omsc_tests_NOT_BUILT omsc_tests_NOT_BUILT)
endif()
