#pragma once
#ifndef OPT_CONTEXT_H
#define OPT_CONTEXT_H


#include "ast.h"      // FunctionEffects, OptMaxConfig, etc.
#include "cfctre.h"   // CTValue, CTEngine
#include "egraph.h"   // EGraph, SaturationConfig, egraph::optimizeProgram, etc.
#include "opt_pass.h" // AnalysisKey, PassMetadata, IRInvariant
#include <any>
#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>

namespace omscript {

// BuiltinEffects — per-builtin effect descriptor
struct BuiltinEffects {
    bool constFoldable = false; ///< Can be evaluated at compile time
    bool readsMemory   = false; ///< Accesses heap/array/string memory
    bool writesMemory  = false; ///< Mutates heap/array/string memory
    bool hasIO         = false; ///< Performs observable I/O
    bool mayThrow      = false; ///< May raise / panic / abort / exit
    bool noReturn      = false; ///< Provably never returns to the caller
    bool allocates     = false; ///< Performs heap allocation
    bool deallocates   = false; ///< Releases heap memory
};

// BuiltinEffectTable — static singleton lookup table; O(1) by name, unknown → all false
class BuiltinEffectTable {
public:
    /// Return the effect descriptor for built-in @p name.
    /// For unknown names all fields are false (conservatively impure).
    static const BuiltinEffects& get(const std::string& name) noexcept;

    // ── Convenience predicates ────────────────────────────────────────────

    /// True when calling @p name cannot prevent the containing function from
    /// being const-evaluated (replaces kPureBuiltins look-up).
    static bool isPure(const std::string& name) noexcept {
        return get(name).constFoldable;
    }

    /// True when calling @p name makes the containing function impure for
    /// const-eval purposes (replaces kImpureBuiltins look-up).
    static bool isImpure(const std::string& name) noexcept {
        const auto& e = get(name);
        return e.writesMemory || e.hasIO;
    }

    /// True when @p name performs I/O (replaces kIOBuiltins look-up).
    static bool isIO(const std::string& name) noexcept {
        return get(name).hasIO;
    }

    /// True when @p name mutates heap memory (replaces kMutatingBuiltins).
    static bool isMutating(const std::string& name) noexcept {
        const auto& e = get(name);
        return e.writesMemory && !e.hasIO;
    }

    /// True when @p name only reads memory (replaces kReadBuiltins).
    static bool isReadOnly(const std::string& name) noexcept {
        const auto& e = get(name);
        return e.readsMemory && !e.writesMemory && !e.hasIO;
    }

    /// True when @p name may throw, panic, abort, or otherwise unwind/terminate.
    static bool mayThrow(const std::string& name) noexcept {
        return get(name).mayThrow;
    }

    /// True when @p name provably never returns (panic/abort/exit).
    static bool noReturn(const std::string& name) noexcept {
        return get(name).noReturn;
    }

    /// True when @p name allocates heap memory.
    static bool allocates(const std::string& name) noexcept {
        return get(name).allocates;
    }

    /// True when @p name deallocates heap memory.
    static bool deallocates(const std::string& name) noexcept {
        return get(name).deallocates;
    }

    /// True when @p name is an integer-width cast intrinsic of the form
    /// `iN` or `uN` (where N is 1..256), or a `__tw_*` / `__tf_*`
    /// width-specific intrinsic generated by the compiler.
    /// These names are always pure / const-foldable, but cannot be enumerated
    /// statically because N is arbitrary; they are handled dynamically.
    static bool isWidthCastName(const std::string& nm) noexcept {
        // __tw_* and __tf_* generated width/type-specific builtins.
        if (nm.size() > 5 &&
            (nm.substr(0, 5) == "__tw_" || nm.substr(0, 5) == "__tf_"))
            return true;
        // iN / uN width casts (e.g. i8, u32, i128).
        if (nm.size() < 2) return false;
        if (nm[0] != 'i' && nm[0] != 'u') return false;
        int bw = 0;
        for (size_t j = 1; j < nm.size(); ++j) {
            if (nm[j] < '0' || nm[j] > '9') return false;
            bw = bw * 10 + (nm[j] - '0');
            if (bw > 256) return false;
        }
        return bw >= 1 && bw <= 256;
    }

private:
    BuiltinEffectTable() = delete;
    static const std::unordered_map<std::string, BuiltinEffects>& table() noexcept;
};

// ValueRange — conservative closed interval [lo, hi] for an integer value
struct ValueRange {
    int64_t lo = std::numeric_limits<int64_t>::min(); ///< Inclusive lower bound
    int64_t hi = std::numeric_limits<int64_t>::max(); ///< Inclusive upper bound

    /// True when the range has been narrowed below the full i64 range.
    bool isNarrowed() const noexcept {
        return lo > std::numeric_limits<int64_t>::min() ||
               hi < std::numeric_limits<int64_t>::max();
    }

    /// Intersect two ranges: the tightest bound satisfying both constraints.
    static ValueRange intersect(const ValueRange& a, const ValueRange& b) noexcept {
        return {std::max(a.lo, b.lo), std::min(a.hi, b.hi)};
    }

    /// Join two ranges: the widest bound covering both.
    static ValueRange join(const ValueRange& a, const ValueRange& b) noexcept {
        return {std::min(a.lo, b.lo), std::max(a.hi, b.hi)};
    }

    /// True when the range is empty (no value satisfies it).
    bool isEmpty() const noexcept { return lo > hi; }

    /// True when the value is always non-negative.
    bool isNonNeg() const noexcept { return lo >= 0; }

    /// True when the value is a single known constant.
    bool isConst() const noexcept { return lo == hi; }

    /// Return the constant value when isConst() is true.
    int64_t constVal() const noexcept { return lo; }
};

// FunctionFacts — per-function analysis results (populated by Orchestrator, read by CodeGenerator)
struct FunctionFacts {
    // ── Purity / effect ───────────────────────────────────────────────────
    bool isPure          = false; ///< No side effects; safe for LLVM readnone
    bool isConstFoldable = false; ///< Can be const-evaluated when args known
    FunctionEffects effects;      ///< Detailed effect summary from inferFunctionEffects

    // ── Constant return values ────────────────────────────────────────────
    std::optional<int64_t>     constIntReturn;    ///< Always-constant int return
    std::optional<std::string> constStringReturn; ///< Always-constant string return
    std::optional<CTValue>     uniformCTReturn;   ///< CF-CTRE uniform return value

    // ── Reachability ──────────────────────────────────────────────────────
    bool isDead = false; ///< Unreachable from any entry point (CF-CTRE Phase 7)

    // ── CF-CTRE: was this function successfully CT-evaluated? ─────────────
    bool foldedByCFCTRE = false; ///< Had ≥1 successful compile-time call

    // ── Value range for the return value ─────────────────────────────────
    std::optional<ValueRange> returnRange; ///< Known bounds on the return value
};

// AnalysisValidity — validity flags for each analysis pass; cleared when the AST changes
struct AnalysisValidity {
    bool stringTypes     = false; ///< preAnalyzeStringTypes() has run
    bool arrayTypes      = false; ///< preAnalyzeArrayTypes() has run
    bool constantReturns = false; ///< analyzeConstantReturnValues() has run
    bool purity          = false; ///< autoDetectConstEvalFunctions() has run
    bool effects         = false; ///< inferFunctionEffects() has run
    bool synthesis       = false; ///< runSynthesisPass() has run
    bool cfctre          = false; ///< runCFCTRE() has run
    bool egraph          = false; ///< egraph::optimizeProgram() has run
    bool rangeAnalysis   = false; ///< Value range analysis has run
    bool rlc             = false; ///< Region Lifetime Coalescing pass has run
    bool dce             = false; ///< Dead Code Elimination pass has run
    bool cse             = false; ///< Common Subexpression Elimination pass has run
    bool algSimp         = false; ///< Algebraic Simplification pass has run
    bool copyProp        = false; ///< Copy Propagation pass has run

    // ── Dispatch table ────────────────────────────────────────────────────
    bool* fieldFor(std::string_view fact) noexcept {
        struct Row { std::string_view name; bool AnalysisValidity::* field; };
        static constexpr Row kTable[] = {
            {"string_types",     &AnalysisValidity::stringTypes    },
            {"array_types",      &AnalysisValidity::arrayTypes     },
            {"constant_returns", &AnalysisValidity::constantReturns},
            {"purity",           &AnalysisValidity::purity         },
            {"effects",          &AnalysisValidity::effects        },
            {"synthesis",        &AnalysisValidity::synthesis      },
            {"cfctre",           &AnalysisValidity::cfctre         },
            {"egraph",           &AnalysisValidity::egraph         },
            {"range_analysis",   &AnalysisValidity::rangeAnalysis  },
            {"rlc",              &AnalysisValidity::rlc            },
            {"dce",              &AnalysisValidity::dce            },
            {"cse",              &AnalysisValidity::cse            },
            {"alg_simp",         &AnalysisValidity::algSimp        },
            {"copy_prop",        &AnalysisValidity::copyProp       },
        };
        for (const auto& row : kTable) {
            if (row.name == fact)
                return &(this->*(row.field));
        }
        return nullptr;
    }
    const bool* fieldFor(std::string_view fact) const noexcept {
        return const_cast<AnalysisValidity*>(this)->fieldFor(fact);
    }

    // ── Public interface ──────────────────────────────────────────────────

    /// Mark all facts invalid (call when the AST is modified).
    void invalidateAll() noexcept { *this = {}; }

    /// Mark only function-body-derived facts invalid (for single-function edits).
    void invalidateFunctionFacts() noexcept {
        // Excludes string_types, array_types, and rlc (structural facts that survive single-function edits).
        static constexpr std::string_view kBodyFacts[] = {
            "constant_returns", "purity", "effects", "cfctre", "range_analysis"
        };
        for (std::string_view f : kBodyFacts)
            if (bool* fp = fieldFor(f)) *fp = false;
    }

    /// Return true if @p fact is currently valid. Unknown fact names return false.
    bool isValid(std::string_view fact) const noexcept {
        const bool* fp = fieldFor(fact);
        return fp && *fp;
    }

    /// Mark @p fact invalid; cascades through the dependency graph if attached. Unknown names ignored.
    void invalidate(std::string_view fact) noexcept {
        auto markInvalid = [this](std::string_view f) noexcept {
            if (bool* fp = fieldFor(f)) *fp = false;
        };
        if (depGraph_) {
            for (const auto& d : depGraph_->getAllDependents(std::string(fact)))
                markInvalid(d);
        } else {
            markInvalid(fact);
        }
    }

    /// Mark @p fact valid. Unknown fact names are silently ignored.
    void markValid(std::string_view fact) noexcept {
        if (bool* fp = fieldFor(fact)) *fp = true;
    }

    /// Attach a dependency graph so that invalidating a fact also invalidates
    /// all transitively dependent facts.  Non-owning pointer.
    void setDependencyGraph(const AnalysisDependencyGraph* graph) noexcept {
        depGraph_ = graph;
    }
    const AnalysisDependencyGraph* dependencyGraph() const noexcept {
        return depGraph_;
    }

private:
    const AnalysisDependencyGraph* depGraph_ = nullptr;
};

// AnalysisCache — typed key-value store (std::any values) for analysis results with invalidation
class AnalysisCache {
public:
    AnalysisCache()  = default;
    ~AnalysisCache() = default;

    // Non-copyable (large state).
    AnalysisCache(const AnalysisCache&)            = delete;
    AnalysisCache& operator=(const AnalysisCache&) = delete;

    // Movable.
    AnalysisCache(AnalysisCache&&)            = default;
    AnalysisCache& operator=(AnalysisCache&&) = default;

    /// Store a value of type T under key @p k, replacing any existing entry.
    template<class T>
    void put(const AnalysisKey& k, T value) {
        store_[k] = std::move(value);
    }

    /// Retrieve a const pointer to T for key @p k; nullptr if not found or wrong type.
    template<class T>
    const T* get(const AnalysisKey& k) const noexcept {
        auto it = store_.find(k);
        if (it == store_.end()) return nullptr;
        return std::any_cast<T>(&it->second);
    }

    /// Retrieve a mutable pointer to T for key @p k; nullptr if not found or wrong type.
    template<class T>
    T* get(const AnalysisKey& k) noexcept {
        auto it = store_.find(k);
        if (it == store_.end()) return nullptr;
        return std::any_cast<T>(&it->second);
    }

    /// Return true if the cache contains an entry for key @p k.
    bool has(const AnalysisKey& k) const noexcept {
        return store_.count(k) > 0;
    }

    /// Remove cached value for @p k; also evicts transitive dependents if a dep-graph is attached.
    void invalidate(const AnalysisKey& k) noexcept {
        if (depGraph_) {
            for (const auto& dep : depGraph_->getAllDependents(k))
                store_.erase(dep);
        } else {
            store_.erase(k);
        }
    }

    /// Remove all cached values whose keys appear in @p meta.invalidates_.
    void invalidateByContract(const PassMetadata& meta) noexcept {
        for (const char* key : meta.invalidates_)
            invalidate(key);
    }

    /// Attach a dependency graph (non-owning); cascades invalidation. Passing nullptr detaches.
    void setDependencyGraph(const AnalysisDependencyGraph* graph) noexcept {
        depGraph_ = graph;
    }

    const AnalysisDependencyGraph* dependencyGraph() const noexcept {
        return depGraph_;
    }

    /// Remove all cached values.
    void clear() noexcept { store_.clear(); }

    /// Return the number of entries currently in the cache.
    size_t size() const noexcept { return store_.size(); }

private:
    std::unordered_map<AnalysisKey, std::any> store_;
    const AnalysisDependencyGraph*            depGraph_ = nullptr;
};

// EGraphConfig — public mirror of egraph::SaturationConfig; defaults match egraph::optimizeExpression
struct EGraphConfig {
    size_t maxNodes            = 10000; ///< Node limit per expression graph
    size_t maxIterations       = 15;    ///< Saturation iteration cap
    bool   enableConstFolding  = true;  ///< Enable constant-folding during saturation
};

// EGraphStats — per-run statistics; reset at start of optimizeProgram/optimizeFunction
struct EGraphStats {
    unsigned expressionsAttempted  = 0; ///< Expressions submitted to the e-graph
    unsigned expressionsSimplified = 0; ///< Expressions that changed after extraction
    unsigned expressionsSkipped    = 0; ///< Expressions not representable in the e-graph
    unsigned functionsChanged      = 0; ///< Functions with ≥1 simplified expression
    size_t   rulesApplied          = 0; ///< Total rewrites across all saturations

    void reset() noexcept { *this = {}; }
};

// EGraphSubsystem — e-graph equality-saturation optimizer owned by OptimizationContext
class EGraphSubsystem {
public:
    EGraphSubsystem()  = default;
    ~EGraphSubsystem() = default;

    // ── Configuration ─────────────────────────────────────────────────────

    /// Replace the current configuration before any optimize* call.
    void setConfig(EGraphConfig cfg) noexcept { config_ = cfg; }
    const EGraphConfig& config() const noexcept { return config_; }

    /// Build egraph::SaturationConfig from our config for internal use.
    egraph::SaturationConfig toSaturationConfig() const noexcept {
        egraph::SaturationConfig sc;
        sc.maxNodes            = config_.maxNodes;
        sc.maxIterations       = config_.maxIterations;
        sc.enableConstantFolding = config_.enableConstFolding;
        return sc;
    }

    /// Build egraph::EGraphOptContext from our config and pure-user-funcs.
    egraph::EGraphOptContext toOptContext() const noexcept {
        egraph::EGraphOptContext ctx;
        ctx.config        = toSaturationConfig();
        ctx.pureUserFuncs = pureUserFuncs_.empty() ? nullptr : &pureUserFuncs_;
        return ctx;
    }

    // ── Pure-user-function registry ───────────────────────────────────────

    /// Replace the set of known-pure user-defined function names.
    /// Called by the Orchestrator after the purity pass so that the e-graph
    /// can include expressions involving these functions.
    void setPureUserFuncs(std::unordered_set<std::string> funcs) {
        pureUserFuncs_ = std::move(funcs);
    }

    const std::unordered_set<std::string>& pureUserFuncs() const noexcept {
        return pureUserFuncs_;
    }

    // ── Entry points ──────────────────────────────────────────────────────

    /// Optimize a single AST expression.  Returns the simplified expression
    /// (or the original if no improvement was found / not representable).
    std::unique_ptr<Expression> optimizeExpression(const Expression* expr);

    /// Optimize all expressions in one function's body.
    void optimizeFunction(FunctionDecl* func);

    /// Optimize all functions in a program.  Resets stats before running.
    void optimizeProgram(Program* program);

    // ── Statistics ────────────────────────────────────────────────────────

    const EGraphStats& stats() const noexcept { return stats_; }

    /// Reset statistics (called automatically at the start of optimizeProgram).
    void resetStats() noexcept { stats_.reset(); }

private:
    EGraphConfig                    config_;
    EGraphStats                     stats_;
    std::unordered_set<std::string> pureUserFuncs_;
};

// OptimizationContext — owns FunctionFacts, AnalysisValidity, EGraphSubsystem, and CTEngine ref
class OptimizationContext {
public:
    explicit OptimizationContext() = default;
    ~OptimizationContext()         = default;

    // Non-copyable (large state, always passed by pointer or reference).
    OptimizationContext(const OptimizationContext&)            = delete;
    OptimizationContext& operator=(const OptimizationContext&) = delete;

    // ── Fact registration (called by analysis passes) ─────────────────────

    /// Register or update all facts for @p funcName.
    void setFacts(const std::string& funcName, FunctionFacts facts) {
        facts_[funcName] = std::move(facts);
    }

    /// Return the facts for @p funcName, or a default-constructed FunctionFacts if unknown.
    const FunctionFacts& getFacts(const std::string& funcName) const noexcept {
        static const FunctionFacts kDefault;
        auto it = facts_.find(funcName);
        return (it != facts_.end()) ? it->second : kDefault;
    }

    /// Mutable access — used by the Orchestrator to incrementally populate.
    FunctionFacts& mutableFacts(const std::string& funcName) {
        return facts_[funcName];
    }

    // ── High-level query API (used by CodeGenerator during IR emission) ───

    /// True when @p funcName is pure (no side effects of any kind).
    bool isPure(const std::string& funcName) const noexcept {
        auto it = facts_.find(funcName);
        return (it != facts_.end()) && it->second.isPure;
    }

    /// True when @p funcName can be const-evaluated with constant args.
    bool isConstFoldable(const std::string& funcName) const noexcept {
        auto it = facts_.find(funcName);
        return (it != facts_.end()) && it->second.isConstFoldable;
    }

    /// Return the always-constant integer return value, if known.
    std::optional<int64_t> constIntReturn(const std::string& funcName) const noexcept {
        auto it = facts_.find(funcName);
        if (it == facts_.end()) return std::nullopt;
        return it->second.constIntReturn;
    }

    /// Return the always-constant string return value, if known.
    std::optional<std::string> constStringReturn(const std::string& funcName) const noexcept {
        auto it = facts_.find(funcName);
        if (it == facts_.end()) return std::nullopt;
        return it->second.constStringReturn;
    }

    /// Return the CF-CTRE uniform return value (may be any CTValue), if known.
    std::optional<CTValue> uniformCTReturn(const std::string& funcName) const noexcept {
        auto it = facts_.find(funcName);
        if (it == facts_.end()) return std::nullopt;
        return it->second.uniformCTReturn;
    }

    /// Return the known integer return range for @p funcName, if available.
    std::optional<ValueRange> returnRange(const std::string& funcName) const noexcept {
        auto it = facts_.find(funcName);
        if (it == facts_.end()) return std::nullopt;
        return it->second.returnRange;
    }

    /// True when @p funcName is unreachable from any entry point.
    bool isDead(const std::string& funcName) const noexcept {
        auto it = facts_.find(funcName);
        return (it != facts_.end()) && it->second.isDead;
    }

    /// Return the effect summary for @p funcName.
    const FunctionEffects& effects(const std::string& funcName) const noexcept {
        static const FunctionEffects kDefault;
        auto it = facts_.find(funcName);
        return (it != facts_.end()) ? it->second.effects : kDefault;
    }

    // ── Validity tracking ─────────────────────────────────────────────────

    AnalysisValidity&       validity()       noexcept { return validity_; }
    const AnalysisValidity& validity() const noexcept { return validity_; }

    // ── CTEngine reference ────────────────────────────────────────────────
    /// Non-owning pointer to the CTEngine; set once before the Orchestrator runs.
    void setCTEngine(CTEngine* engine) noexcept { ctEngine_ = engine; }
    CTEngine* ctEngine() const noexcept { return ctEngine_; }

    // ── CTEngine query proxies — all return safe defaults when ctEngine_ is null ──

    /// True when @p name is compile-time-pure per CFCTRE (distinct from isPure()).
    bool isCTPure(const std::string& name) const noexcept {
        return ctEngine_ && ctEngine_->isPure(name);
    }

    /// Strength-reduced operator token for @p binExpr, or empty if none found.
    const std::string& cheaperRewrite(const Expression* binExpr) const noexcept {
        static const std::string kEmpty;
        if (!ctEngine_) return kEmpty;
        return ctEngine_->cheaperRewrite(binExpr);
    }

    /// True when CFCTRE determined the then-branch of @p ifStmt is dead.
    bool isThenBranchDead(const Statement* ifStmt) const noexcept {
        return ctEngine_ && ctEngine_->isThenBranchDead(ifStmt);
    }

    /// True when CFCTRE determined the else-branch of @p ifStmt is dead.
    bool isElseBranchDead(const Statement* ifStmt) const noexcept {
        return ctEngine_ && ctEngine_->isElseBranchDead(ifStmt);
    }

    /// Abstract integer exit-range of @p varName in @p fnName; CTInterval::top() if unknown.
    CTInterval getExitRange(const std::string& fnName,
                            const std::string& varName) const noexcept {
        if (!ctEngine_) return CTInterval::top();
        return ctEngine_->getExitRange(fnName, varName);
    }

    /// Execute @p fnName with CT-known @p args; nullopt if ctEngine_ is null or failed.
    std::optional<CTValue> executeFunction(const std::string&          fnName,
                                           const std::vector<CTValue>& args) const {
        if (!ctEngine_) return std::nullopt;
        return ctEngine_->executeFunction(fnName, args);
    }

    /// Uniform-return-value map from CFCTRE; empty map when ctEngine_ is null.
    const std::unordered_map<std::string, CTValue>& uniformReturnValues() const noexcept {
        static const std::unordered_map<std::string, CTValue> kEmpty;
        if (!ctEngine_) return kEmpty;
        return ctEngine_->uniformReturnValues();
    }

    // ── Iteration helpers ─────────────────────────────────────────────────
    const std::unordered_map<std::string, FunctionFacts>& allFacts() const noexcept {
        return facts_;
    }

    // ── E-Graph subsystem ─────────────────────────────────────────────────
    EGraphSubsystem&       egraph()       noexcept { return egraph_; }
    const EGraphSubsystem& egraph() const noexcept { return egraph_; }

    // ── Analysis cache ────────────────────────────────────────────────────
    AnalysisCache&       cache()       noexcept { return cache_; }
    const AnalysisCache& cache() const noexcept { return cache_; }

    // ── Analysis dependency graph — non-owning; shared by validity_ and cache_ ──
    void setDependencyGraph(const AnalysisDependencyGraph* graph) noexcept {
        validity_.setDependencyGraph(graph);
        cache_.setDependencyGraph(graph);
    }
    const AnalysisDependencyGraph* dependencyGraph() const noexcept {
        return cache_.dependencyGraph();
    }

private:
    std::unordered_map<std::string, FunctionFacts> facts_;
    AnalysisValidity validity_;
    CTEngine*        ctEngine_ = nullptr;
    EGraphSubsystem  egraph_;
    AnalysisCache    cache_;
};

} // namespace omscript

#endif // OPT_CONTEXT_H
