#ifndef VERSION_H
#define VERSION_H

#define OMSCRIPT_VERSION_MAJOR 1
#define OMSCRIPT_VERSION_MINOR 7
#define OMSCRIPT_VERSION_PATCH 0

#ifndef OMSC_VERSION
#define OMSC_VERSION "1.7.0"
#endif

#define OMSCRIPT_VERSION_STRING OMSC_VERSION

#endif // VERSION_H
