#ifndef VERSION_H
#define VERSION_H

#define OMSCRIPT_VERSION_MAJOR 2
#define OMSCRIPT_VERSION_MINOR 4
#define OMSCRIPT_VERSION_PATCH 1

#ifndef OMSC_VERSION
#define OMSC_VERSION "2.4.1"
#endif

#define OMSCRIPT_VERSION_STRING OMSC_VERSION

#endif // VERSION_H
