#pragma once

#ifndef VERSION_H
#define VERSION_H

#define OMSCRIPT_VERSION_MAJOR 4
#define OMSCRIPT_VERSION_MINOR 3
#define OMSCRIPT_VERSION_PATCH 2

#ifndef OMSC_VERSION
#define OMSC_VERSION "4.3.2"
#endif

#define OMSCRIPT_VERSION_STRING OMSC_VERSION

#endif // VERSION_H
