name: Run Tests

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            llvm-18-dev \
            clang-18 \
            gcc \
            mold \

      - name: Build omsc from source
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=/usr/lib/llvm-18/cmake -DLTO=ON
          cmake --build build --parallel $(nproc)

      - name: Run integration tests
        run: bash run_tests.sh

      - name: Run benchmarks (omsc vs C)
        run: BENCH_RUNS=5 BENCH_WARMUP=1 bash test.sh
