name: Run Tests

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x test.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang

      # OPTIONAL: install omsc if needed
      - name: Install omsc
        run: |
          curl -L -o omsc.tar.gz https://github.com/RyAnPr1Me/omscript/releases/download/v2.6.1/omsc-2.6.1-linux-x86_64.tar.gz
          tar -xzf omsc.tar.gz
          chmod +x omsc-linux-x86_64
          sudo mv omsc-linux-x86_64 /usr/local/bin/omsc

      - name: Run tests
        run: ./test.sh
